sudo: required
services:
  - docker

before_install:
  - docker build -t momosh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run momosh/react-test npm test -- --coverage

after_success:
  - docker build -t momosh/multi-client ./client
  - docker build -t momosh/multi-nginx ./nginx 
  - docker build -t momosh/multi-server ./server 
  - docker build -t momosh/multi-worker ./worker 
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push momosh/multi-client
  - docker push momosh/multi-nginx
  - docker push momosh/multi-server
  - docker push momosh/multi-worker